# Q1. Create an array having consecutive natural numbers of size 6x3 and print it

In [0]:
import numpy as np   # we use shortform

arr1 = np.arange(18).reshape(6,3)
print("arr1:{}".format(arr1))

#Q2 Rename alll the coumns in the dataset as per your wish and save it in another dataframe and name it df2

In [0]:
import pandas as pd

df = pd.read_excel("Week 1 Dataset.xlsx")

df2 = df.rename(columns={"Name":"Person_Name","Income per month": "Monthly_Income","State":"State_Name","Age":"Person_Age","Sex":"Person_sex","State":"State_name","Number of siblings":" Sibling_number"})

df2

#Q3: After you have created df2, make the same changes in the original dataframe using the inplace.

In [0]:

import pandas as pd

df = pd.read_excel("Week 1 Dataset.xlsx")

df.rename(columns={"Name":"Person_Name","Income per month": "Monthly_Income","State":"State_Name","Age":"Person_Age","Sex":"Person_sex","State":"State_name","Number of siblings":" Sibling_number"},inplace = 'True')

df

#Q4   Show only the columns information, sex and number of siblings

In [0]:
import pandas as pd

df = pd.read_excel("Week 1 Dataset.xlsx")


df[["Name","Sex","Number of siblings"]]


#Q5  Use iloc method to print data from column 1 to 4 and rows 3 to 9
---

In [0]:
import pandas as pd

df = pd.read_excel("Week 1 Dataset.xlsx")

df.iloc[3:10,1:4]

#Q6  Find the total value count of number of siblings in the given dataset

In [0]:

import pandas as pd

df = pd.read_excel("Week 1 Dataset.xlsx")

df["Number of siblings"].sum()

#Q7: What are dependent and independent varibles in our dataset?

Independent variables : Income per month, State, Age,Sex 

Dependent variables : Number of Siblings

#Q8: Mention all your finding from the above given heatmap.


1)People with higher income per month tend to have less number of siblings

2)People with higher income are likely to be younger

3)People who are older are likely to have more siblings